/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arthu
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */

private question[] questions;
private int indexQuestionCourante = 0;
private int scores = 0;




public FenetreQuiz() {
    initComponents();
    


    
    questions = new question[] {
        new question("Capitale de la France ?",
                     "Londres", "Berlin", "Paris", "Madrid", 3),

        new question("2 + 2 = ?",
                     "3", "4", "5", "6", 2),

        new question("Couleur du ciel ?",
                     "Vert", "Bleu", "Rouge", "Jaune",2 ),

        new question("Ta mère a 4 enfants : Lundi, Mardi, Mercredi et ?",
                     "Toi", "Jeudi", "Mercredi Adams", "Github", 1),

        new question("Quelle est la meilleure matière ?",
                     "Maths", "Physique", "Culture Numérique", "Droit", 3)
    };

    
    afficherQuestionCourante();
}




private void afficherQuestionCourante() {

   
    question q = questions[indexQuestionCourante];

   
    question.setText(q.getintitule());

   
    Butrep1.setText(q.get1());
    butrep2.setText(q.get2());
    butrep3.setText(q.get3());
    butrep4.setText(q.get4());

    
    Butrep1.setEnabled(true);
    butrep2.setEnabled(true);
    butrep3.setEnabled(true);
    butrep4.setEnabled(true);
}

    
 
    

private void verifierReponse(int choix) {

    
    question q = questions[indexQuestionCourante];

    
    if (choix == q.getreponse()) {
        scores++;  
        feedback.setText("Bonne réponse !");
        score.setText("Score : " + scores);
    } else {
        feedback.setText("Mauvaise réponse...");
    }

   
    Butrep1.setEnabled(false);
    butrep2.setEnabled(false);
    butrep3.setEnabled(false);
    butrep4.setEnabled(false);
}
private void passerQuestionSuivante() {

   
    indexQuestionCourante++;

    
    if (indexQuestionCourante >= questions.length) {

     
        indexQuestionCourante = questions.length - 1;

    
        feedback.setText("Quiz terminé ! Score : " + scores + " / " + questions.length);

        
        Butrep1.setEnabled(false);
        butrep2.setEnabled(false);
        butrep3.setEnabled(false);
        butrep4.setEnabled(false);

        
        questsuiv.setEnabled(false);

    } else {
     
        feedback.setText("");

     
        afficherQuestionCourante();
    }

}




    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        Butrep1 = new javax.swing.JButton();
        butrep2 = new javax.swing.JButton();
        butrep3 = new javax.swing.JButton();
        butrep4 = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        questsuiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        question.setText("jLabel1");

        Butrep1.setText("jButton1");
        Butrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butrep1ActionPerformed(evt);
            }
        });

        butrep2.setText("jButton2");
        butrep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrep2ActionPerformed(evt);
            }
        });

        butrep3.setText("jButton3");
        butrep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrep3ActionPerformed(evt);
            }
        });

        butrep4.setText("jButton4");
        butrep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butrep4ActionPerformed(evt);
            }
        });

        feedback.setText(" ");

        score.setText("score");

        questsuiv.setText("suivant");
        questsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questsuivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Butrep1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(butrep2)
                        .addGap(34, 34, 34)
                        .addComponent(butrep3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questsuiv)
                            .addComponent(butrep4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(question)
                .addGap(42, 42, 42)
                .addComponent(feedback)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butrep1)
                    .addComponent(butrep2)
                    .addComponent(butrep3)
                    .addComponent(butrep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(questsuiv)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butrep1ActionPerformed
      verifierReponse(1);
    }//GEN-LAST:event_Butrep1ActionPerformed

    private void butrep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrep2ActionPerformed
       verifierReponse(2);
    }//GEN-LAST:event_butrep2ActionPerformed

    private void butrep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrep3ActionPerformed
       verifierReponse(3);
    }//GEN-LAST:event_butrep3ActionPerformed

    private void butrep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butrep4ActionPerformed
        verifierReponse(4);
     
    }//GEN-LAST:event_butrep4ActionPerformed

    private void questsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questsuivActionPerformed
       passerQuestionSuivante();


    }//GEN-LAST:event_questsuivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butrep1;
    private javax.swing.JButton butrep2;
    private javax.swing.JButton butrep3;
    private javax.swing.JButton butrep4;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel question;
    private javax.swing.JButton questsuiv;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables


}


