/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arthu
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
 private question[] questions;
 private int indexQuestionCourante = 0;
 private scores =0;
 
 public FenetreQuiz() {
        initComponents();
       

    questions = new question[] {
        new question("Capitale de la France ?",
                     "Londres", "Berlin", "Paris", "Madrid", 3),
        new question("2 + 2 = ?",
                     "3", "4", "5", "6", 2),
        new question("Couleur du ciel ?",
                     "Vert", "Bleu", "Rouge", "Jaune", 2),
            
        new question("Ta mere a 4 enfants :Lundi ,mardi mercredi et ? ",
                     "toi", "jeudi", "Mercredi adams", "Githuub",1),
        new question ("Quelle est la meilleure matiere ? ",
                      "maths", "physique","Culture numerique","droit",3),
       
      
                   };
    question q = questions[indexQuestionCourante];
    Question.setText(q.getintitule());
    Butrep1.setText(q.get1());
    butrep2.setText(q.get2());
    butrep3.setText(q.get3());
    butrep4.setText(q.get4());
    
 }
    

private void verifrep(){
    question q = tabquestions[indexQuestionCourante];
    
    

    // Réactive les 4 boutons
   
    }


              
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question = new javax.swing.JLabel();
        Butrep1 = new javax.swing.JButton();
        butrep2 = new javax.swing.JButton();
        butrep3 = new javax.swing.JButton();
        butrep4 = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        questsuiv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Question.setText("jLabel1");

        Butrep1.setText("jButton1");
        Butrep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butrep1ActionPerformed(evt);
            }
        });

        butrep2.setText("jButton2");

        butrep3.setText("jButton3");

        butrep4.setText("jButton4");

        feedback.setText("jLabel1");

        score.setText("jLabel1");

        questsuiv.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Butrep1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butrep2)
                                .addGap(26, 26, 26)
                                .addComponent(butrep3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(questsuiv)
                                    .addComponent(butrep4))))))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(score)
                .addGap(18, 18, 18)
                .addComponent(Question)
                .addGap(38, 38, 38)
                .addComponent(feedback)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butrep1)
                    .addComponent(butrep2)
                    .addComponent(butrep3)
                    .addComponent(butrep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(questsuiv)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Butrep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butrep1ActionPerformed
       verif_rep(3);
    }//GEN-LAST:event_Butrep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butrep1;
    private javax.swing.JLabel Question;
    private javax.swing.JButton butrep2;
    private javax.swing.JButton butrep3;
    private javax.swing.JButton butrep4;
    private javax.swing.JLabel feedback;
    private javax.swing.JButton questsuiv;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables


}



