/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author arthu
 */
public class mini_projet1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mini_projet1.class.getName());

    /**
     * Creates new form mini_projet1
     */
    public mini_projet1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_test = new javax.swing.JButton();
        texte_exact = new javax.swing.JLabel();
        nb_exact = new javax.swing.JLabel();
        texte_haut = new javax.swing.JLabel();
        nb_haut = new javax.swing.JLabel();
        texte_bas = new javax.swing.JLabel();
        nb_bas = new javax.swing.JLabel();
        nb_tentative = new javax.swing.JLabel();
        texte_tentative = new javax.swing.JLabel();
        bouton_reco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_intro.setText("Trouvez le code en moins de 5 tentatives ");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, 20));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 30));

            up_chiffre_2.setText("/\\");
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 30));

                up_chiffre_3.setText("/\\");
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, 30));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, 30));

                        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_1.setText("jLabel1");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, 80));

                        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_2.setText("jLabel2");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 50, 80));

                        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_3.setText("jLabel3");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 50, 80));

                        texte_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_4.setText("jLabel4");
                        texte_chiffre_4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 50, 80));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 30));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 80, 30));

                        down_chiffre_3.setText("\\/");
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 80, 30));

                        down_chiffre_4.setText("\\/");
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, 30));

                        bouton_test.setText("Tester");
                        bouton_test.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 100, 40));

                        texte_exact.setText("Nombre de chiffres exactes : ");
                        getContentPane().add(texte_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, -1));

                        nb_exact.setText("0");
                        getContentPane().add(nb_exact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

                        texte_haut.setText("Nombre de chiffres trop hauts : ");
                        getContentPane().add(texte_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

                        nb_haut.setText("0");
                        getContentPane().add(nb_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

                        texte_bas.setText("Nombre de chiffres trop bas : ");
                        getContentPane().add(texte_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

                        nb_bas.setText("0");
                        getContentPane().add(nb_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

                        nb_tentative.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        nb_tentative.setText("0 / 5");
                        nb_tentative.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                        getContentPane().add(nb_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 50, 40));

                        texte_tentative.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_tentative.setText("Tentatives");
                        texte_tentative.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
                        getContentPane().add(texte_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 80, 40));

                        bouton_reco.setText("Recommencer");
                        getContentPane().add(bouton_reco, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void bouton_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mini_projet1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_reco;
    private javax.swing.JButton bouton_test;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel nb_bas;
    private javax.swing.JLabel nb_exact;
    private javax.swing.JLabel nb_haut;
    private javax.swing.JLabel nb_tentative;
    private javax.swing.JLabel texte_bas;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_exact;
    private javax.swing.JLabel texte_haut;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_tentative;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
